// Shared test utilities for motel integration tests.
//
// Since motel is a binary crate, integration tests cannot import its internal
// modules directly. Instead we:
// 1. Start the motel server as a child process using `cargo bin`.
// 2. Re-generate proto types from the same .proto files using tonic::include_proto!.
// 3. Use tonic gRPC clients and reqwest HTTP clients to interact with the server.

use std::net::TcpListener;
use std::process::{Child, Command};
use std::time::Duration;

use prost::Message;

// ---------------------------------------------------------------------------
// Re-exported proto modules (generated by the crate's build.rs, available in
// OUT_DIR at build time). Integration tests share the same OUT_DIR when the
// crate is compiled, so tonic::include_proto! resolves the same generated code.
// If this does not work in your setup, an alternative is to add a [lib] target
// to Cargo.toml or duplicate the proto compilation in a test build script.
// ---------------------------------------------------------------------------

pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.common.v1");
            }
        }
        pub mod resource {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.resource.v1");
            }
        }
        pub mod trace {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.trace.v1");
            }
        }
        pub mod logs {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.logs.v1");
            }
        }
        pub mod metrics {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.metrics.v1");
            }
        }
        pub mod collector {
            pub mod trace {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.collector.trace.v1");
                }
            }
            pub mod logs {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.collector.logs.v1");
                }
            }
            pub mod metrics {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.collector.metrics.v1");
                }
            }
        }
    }
}

pub mod motel {
    pub mod query {
        tonic::include_proto!("motel.query");
    }
}

// Convenience aliases matching the binary crate's conventions.
pub use motel::query as query_proto;
pub use opentelemetry::proto as otel;

// ---------------------------------------------------------------------------
// Port allocation
// ---------------------------------------------------------------------------

/// Bind to port 0 and return the OS-assigned port number.
pub fn get_available_port() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").expect("failed to bind to port 0");
    listener.local_addr().unwrap().port()
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------

/// Start a motel server as a child process with the given ports.
/// Returns the `Child` handle so the caller can kill it when the test finishes.
pub fn start_server_process(grpc_port: u16, http_port: u16, query_port: u16) -> Child {
    let bin = env!("CARGO_BIN_EXE_motel");
    Command::new(bin)
        .args([
            "server",
            "--no-tui",
            "--grpc-addr",
            &format!("0.0.0.0:{grpc_port}"),
            "--http-addr",
            &format!("0.0.0.0:{http_port}"),
            "--query-addr",
            &format!("0.0.0.0:{query_port}"),
        ])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .expect("failed to start motel server")
}

/// Wait until the query gRPC port is accepting connections (up to ~5 seconds).
pub async fn wait_for_server(query_port: u16) {
    let addr = format!("127.0.0.1:{query_port}");
    for _ in 0..50 {
        if tokio::net::TcpStream::connect(&addr).await.is_ok() {
            // Give the server a moment to fully initialize after accepting TCP.
            tokio::time::sleep(Duration::from_millis(50)).await;
            return;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    panic!("server did not become ready on port {query_port} within 5 seconds");
}

/// Convenience: allocate three ports, start the server, wait for readiness.
/// Returns (grpc_port, http_port, query_port, child).
pub async fn start_test_server() -> (u16, u16, u16, Child) {
    let grpc_port = get_available_port();
    let http_port = get_available_port();
    let query_port = get_available_port();
    let child = start_server_process(grpc_port, http_port, query_port);
    wait_for_server(query_port).await;
    (grpc_port, http_port, query_port, child)
}

/// Guard that kills the child process when dropped.
pub struct ServerGuard {
    pub child: Child,
    pub grpc_port: u16,
    pub http_port: u16,
    pub query_port: u16,
}

impl ServerGuard {
    pub async fn start() -> Self {
        let (grpc_port, http_port, query_port, child) = start_test_server().await;
        Self {
            child,
            grpc_port,
            http_port,
            query_port,
        }
    }

    pub async fn start_with_args(extra_args: &[&str]) -> Self {
        let grpc_port = get_available_port();
        let http_port = get_available_port();
        let query_port = get_available_port();
        let bin = env!("CARGO_BIN_EXE_motel");
        let mut cmd = Command::new(bin);
        cmd.args([
            "server",
            "--no-tui",
            "--grpc-addr",
            &format!("0.0.0.0:{grpc_port}"),
            "--http-addr",
            &format!("0.0.0.0:{http_port}"),
            "--query-addr",
            &format!("0.0.0.0:{query_port}"),
        ]);
        for arg in extra_args {
            cmd.arg(arg);
        }
        let child = cmd
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .expect("failed to start motel server");
        wait_for_server(query_port).await;
        Self {
            child,
            grpc_port,
            http_port,
            query_port,
        }
    }

    pub fn grpc_addr(&self) -> String {
        format!("http://127.0.0.1:{}", self.grpc_port)
    }

    pub fn http_base_url(&self) -> String {
        format!("http://127.0.0.1:{}", self.http_port)
    }

    pub fn query_addr(&self) -> String {
        format!("http://127.0.0.1:{}", self.query_port)
    }
}

impl Drop for ServerGuard {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

// ---------------------------------------------------------------------------
// Test data builders
// ---------------------------------------------------------------------------

/// Create a protobuf-encoded `ExportTraceServiceRequest` containing a single
/// span with the given trace_id (16 bytes) and span_name.
pub fn make_resource_spans(trace_id: &[u8], span_name: &str) -> otel::trace::v1::ResourceSpans {
    use otel::common::v1::{AnyValue, KeyValue, any_value::Value};
    use otel::resource::v1::Resource;
    use otel::trace::v1::{ResourceSpans, ScopeSpans, Span};

    ResourceSpans {
        resource: Some(Resource {
            attributes: vec![KeyValue {
                key: "service.name".into(),
                value: Some(AnyValue {
                    value: Some(Value::StringValue("test-service".into())),
                }),
                ..Default::default()
            }],
            ..Default::default()
        }),
        scope_spans: vec![ScopeSpans {
            scope: None,
            spans: vec![Span {
                trace_id: trace_id.to_vec(),
                span_id: vec![1, 2, 3, 4, 5, 6, 7, 8],
                parent_span_id: vec![],
                name: span_name.to_string(),
                kind: 1, // SPAN_KIND_INTERNAL
                start_time_unix_nano: 1_000_000_000,
                end_time_unix_nano: 2_000_000_000,
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    }
}

/// Create an `ExportTraceServiceRequest` ready to send via gRPC or encode for HTTP.
pub fn make_export_trace_request(
    trace_id: &[u8],
    span_name: &str,
) -> otel::collector::trace::v1::ExportTraceServiceRequest {
    otel::collector::trace::v1::ExportTraceServiceRequest {
        resource_spans: vec![make_resource_spans(trace_id, span_name)],
    }
}

/// Create a protobuf-encoded `ExportLogsServiceRequest` containing a single log record.
pub fn make_resource_logs(body: &str) -> otel::logs::v1::ResourceLogs {
    use otel::common::v1::{AnyValue, KeyValue, any_value::Value};
    use otel::logs::v1::{LogRecord, ResourceLogs, ScopeLogs};
    use otel::resource::v1::Resource;

    ResourceLogs {
        resource: Some(Resource {
            attributes: vec![KeyValue {
                key: "service.name".into(),
                value: Some(AnyValue {
                    value: Some(Value::StringValue("test-service".into())),
                }),
                ..Default::default()
            }],
            ..Default::default()
        }),
        scope_logs: vec![ScopeLogs {
            scope: None,
            log_records: vec![LogRecord {
                time_unix_nano: 1_000_000_000,
                observed_time_unix_nano: 1_000_000_000,
                severity_number: 9, // SEVERITY_NUMBER_INFO
                severity_text: "INFO".into(),
                body: Some(AnyValue {
                    value: Some(Value::StringValue(body.to_string())),
                }),
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    }
}

/// Create an `ExportLogsServiceRequest` ready to send.
pub fn make_export_logs_request(body: &str) -> otel::collector::logs::v1::ExportLogsServiceRequest {
    otel::collector::logs::v1::ExportLogsServiceRequest {
        resource_logs: vec![make_resource_logs(body)],
    }
}

/// Create a simple gauge metric for testing.
pub fn make_resource_metrics(metric_name: &str, value: f64) -> otel::metrics::v1::ResourceMetrics {
    use otel::common::v1::{AnyValue, KeyValue, any_value::Value};
    use otel::metrics::v1::{
        Gauge, Metric, NumberDataPoint, ResourceMetrics, ScopeMetrics, number_data_point,
    };
    use otel::resource::v1::Resource;

    ResourceMetrics {
        resource: Some(Resource {
            attributes: vec![KeyValue {
                key: "service.name".into(),
                value: Some(AnyValue {
                    value: Some(Value::StringValue("test-service".into())),
                }),
                ..Default::default()
            }],
            ..Default::default()
        }),
        scope_metrics: vec![ScopeMetrics {
            scope: None,
            metrics: vec![Metric {
                name: metric_name.to_string(),
                description: "test metric".to_string(),
                unit: "1".to_string(),
                data: Some(otel::metrics::v1::metric::Data::Gauge(Gauge {
                    data_points: vec![NumberDataPoint {
                        time_unix_nano: 1_000_000_000,
                        start_time_unix_nano: 0,
                        value: Some(number_data_point::Value::AsDouble(value)),
                        ..Default::default()
                    }],
                })),
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    }
}

/// Create an `ExportMetricsServiceRequest` ready to send.
pub fn make_export_metrics_request(
    metric_name: &str,
    value: f64,
) -> otel::collector::metrics::v1::ExportMetricsServiceRequest {
    otel::collector::metrics::v1::ExportMetricsServiceRequest {
        resource_metrics: vec![make_resource_metrics(metric_name, value)],
    }
}

/// Encode a prost Message to bytes (for HTTP protobuf bodies).
pub fn encode_proto<T: Message>(msg: &T) -> Vec<u8> {
    msg.encode_to_vec()
}
